#!/bin/bash

eval `opam config env`

export PATH=$PATH:${OPENSHIFT_DATA_DIR}bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${OPENSHIFT_DATA_DIR}lib
export CPATH=$LD_LIBRARY_PATH:${OPENSHIFT_DATA_DIR}include

opam install -y camlp4
opam install -y cairo2 uuidm sqlite3
opam install -y eliom

cd $OPENSHIFT_REPO_DIR
make opt
make install.opt
