#!/bin/bash

eval `opam config env`

export  PKG_CONFIG_PATH=${OPENSHIFT_DATA_DIR}lib/pkgconfig
export PATH=$PATH:${OPENSHIFT_DATA_DIR}bin

opam update
opam install -y camlp4
opam install -y cairo2 uuidm sqlite3

opam pin -y add reactiveData https://github.com/ocsigen/reactiveData.git &&\
opam pin -y add tyxml --dev-repo &&\
opam pin -y add js_of_ocaml --dev-repo &&\
opam pin -y add eliom --dev-repo

cd $OPENSHIFT_REPO_DIR
make PREFIX=${OPENSHIFT_DATA_DIR} PORT="${OPENSHIFT_OCAML_IP}:${OPENSHIFT_OCAML_PORT}" opt
make PREFIX=${OPENSHIFT_DATA_DIR} install.opt
