#!/bin/bash

eval `opam config env`

export  PKG_CONFIG_PATH=${OPENSHIFT_DATA_DIR}lib/pkgconfig
export PATH=$PATH:${OPENSHIFT_DATA_DIR}bin

opam install -y camlp4
opam install -y cairo2 uuidm sqlite3
opam install -y eliom

cd $OPENSHIFT_REPO_DIR
make opt
PREFIX=${OPENSHIFT_DATA_DIR} make install.opt
